[package]
name = "on_chain_geo_v1"
version = "1.0.0"
authors = []

[addresses]
my_management_addr='0xb240805074b793270b7f263d732cc113b5a93baffa0a41d554b5d1822ac3d2db'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
